updated_by: chrisl
common_names:
  - Long-Spinneret Ground Spider
classification:
  - name: Arachnida
    rank: class
  - name: Prodidomidae
    rank: family
  - name: Araneae
    rank: order
categories:
  - provisional-name
  - spider
id:
  ns: 53b398f2e35eb12984039d93
